name: Kurztitel
author: Christian Hauser
favicon: #favicon image path (svg)
encoding: utf-8
plugins:
    - jekyll-autoprefixer
    - liquefy
markdown: kramdown
kramdown:
  input: GFM
# keep_files: [css/main.css, js/build/main.min.js]
excerpt_separator: "<!-- more -->"
permalink: /:title/
defaults:
  -
    scope:
      path: ""
      layout: "page"
    values:
      displaytitle: true
sass:
    style: expanded
collections:
    argentinien:
        output: false
    brasilien:
        output: false
    kolumbien:
        output: false
    mexiko:
        output: false
    peru:
        output: false
    forschungstagebuch:
        output: false
