name: Verantwortungsvolle Unternehmensführung in Lateinamerika
author: Christian Hauser
favicon: #favicon image path (svg)
url: http://lehrehtw.github.io
baseurl: /csr-lateinamerika
encoding: utf-8
plugins:
    - jekyll-autoprefixer
    - liquefy
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# keep_files: [css/main.css, js/build/main.min.js]
excerpt_separator: "<!-- more -->"
permalink: /:title/
defaults:
  -
    scope:
      path: ""
      layout: "page"
    values:
      displaytitle: true
      exclude: false
sass:
    style: compressed
collections:
    argentinien:
        output: false
    brasilien:
        output: false
    kolumbien:
        output: false
    mexiko:
        output: false
    peru:
        output: false
    forschungstagebuch:
        output: false
    empfehlungen:
        output: false
